name: 'Maven build action'
description: 'To read maven file and build'
inputs:
  path-to-scan:  # path to scan files
    description: 'path to scan files'
    required: true

  gthub-token:
    description: 'github token'
    required: true

runs:
  using: 'node16'
  main: 'index.js'